### ISSUE TITLE
Responsive not working correctly on mobile

### ISSUE THREAD

**Issue by bomod** [hauntd/youdate-support#1]
Responsive not working correctly on mobile.
For more information, the problem described in the attached pictures.
This happens, when a new user registration.
![42705709_335986806977173_2098126601093906432_n 1](https://user-images.githubusercontent.com/43688256/46237674-5beb9580-c386-11e8-8565-7eb42ec6d6e1.jpg)
![42705709_335986806977173_2098126601093906432_n](https://user-images.githubusercontent.com/43688256/46237675-5beb9580-c386-11e8-90b0-776c8325eb76.jpg)

**Comment by hauntd** [comment]
@bomod Thank you for your report! Fixed (will be in update v1.2.2 or 1.3).

**Comment by bomod** [comment]
You are welcome Bro, Good luck
