### ISSUE TITLE
Theme Inheritance no working (images)

### ISSUE THREAD

**Issue by AngryElephant** [hauntd/youdate-support#10]
i use the custom theme, the base theme is Youdate.

I added some images in custom/static/images but i can't access those images from my theme

` <?= Html::img(['@themeUrl/static/images/test.jpg'], ['class' => '', 'alt' => '']) ?>` is 404

**Comment by AngryElephant** [comment]
Css assets are not loaded in custom theme pages (About, terms ...)

**Comment by hauntd** [comment]
Same as in previous answer: 

Try this: `@web/content/themes/custom/static/images/test.jpg`

**Comment by AngryElephant** [comment]
So it needs to be hard coded ?

**Comment by AngryElephant** [comment]
@extendedThemeUrl is also working. I was looking for a cleaner solution. But it's ok for now

**Comment by hauntd** [comment]
> So it needs to be hard coded ?

You can use `@web/content/...` in case when your static files are not in themes directory.

> @extendedThemeUrl is also working. I was looking for a cleaner solution. But it's ok for now

Yes, that's correct.
