### ISSUE TITLE
Display bugs 

### ISSUE THREAD

**Issue by AngryElephant** [hauntd/youdate-support#11]
I have this kind of bug in many places :

<img width="197" alt="screenshot at oct 06 22-52-26" src="https://user-images.githubusercontent.com/14820782/46573109-8f4ba700-c9ba-11e8-81e7-077d37150c06.png">

I already applied the right charset in db and .env file

**Comment by hauntd** [comment]
Script (framework itself) requires ICU extension v49.1+ (which is kinda old - Nov 2012).

What's your ICU version?

![image](https://user-images.githubusercontent.com/5505601/46575378-f8341e80-c9bc-11e8-9dea-c2f0dab9577c.png)

**Comment by AngryElephant** [comment]
Internationalization support | enabled
version | 1.1.0
ICU version | 4.2.1

**Comment by hauntd** [comment]
Ah, that's bad. ICU 4.2.1 was released about 9 years ago. Yii2 localization component requires v49.1+ (which was released in 2012).

**Comment by AngryElephant** [comment]
wow i will check that, but it's the default version which is proposed with php 7.1 on cpanel
