### ISSUE TITLE
Errors for photo upload not displayed

### ISSUE THREAD

**Issue by AngryElephant** [hauntd/youdate-support#15]
When the image doesn't meet the requirement (too small, too big...) There is no feedback on the page, i had to check the chrome console to see that my image was too small.

Is it normal ?

**Comment by hauntd** [comment]
Added in v1.4
![image](https://user-images.githubusercontent.com/5505601/46960802-fc8cc580-d0a7-11e8-8720-e3dca3adc854.png)
