### ISSUE TITLE
Page Not Found

### ISSUE THREAD

**Issue by miguel1876** [hauntd/youdate-support#18]
Hi.
I am having trouble after installing the script on a local server - MAMP. 
Everything seemed to install correctly, however when I try to access /admin or any other page I get a "Not Found" error.  Apache Rewrite module is enabled so that should not be the culprit. 
Any ideas?   
Please help.

Thank you.

**Comment by AngryElephant** [comment]
Put a test.html page at your root folder first and check if you can access it

**Comment by miguel1876** [comment]
> Put a test.html page at your root folder first and check if you can access it

@AngryElephant Thank you.  Yes I can access test.html

**Comment by hauntd** [comment]
Check your **.env** config file, `ADMIN_PREFIX` key.

EDIT: did you copy .htaccess file?

**Comment by miguel1876** [comment]
Hi Alex.

ADMIN_PREFIX = admin

The /admin, /login and /register pages all have the same  "Not Found" error

**Comment by hauntd** [comment]
"Not found" error displayed by Apache or by script?

**Comment by miguel1876** [comment]
By Apache

https://imgur.com/a/yDWWiiM

**Comment by hauntd** [comment]
Try this .htaccess:

```
<IfModule mod_rewrite.c>
    <IfModule mod_negotiation.c>
        Options -MultiViews
    </IfModule>
    RewriteEngine on
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule . index.php
</IfModule>

<FilesMatch "\.(gitignore|htaccess|env|env-example)$">
    Order Allow,Deny
    Deny from all
</FilesMatch>

Options All -Indexes

```

**Comment by miguel1876** [comment]
Thank you Alex.
That worked perfectly!

**Comment by miguel1876** [comment]
Actually, /login and /register pages are working  
...but now for the /admin page I get a script error

https://imgur.com/a/j12DZNO

**Comment by hauntd** [comment]
Did you run the installer? It should create user with admin rights.

**Comment by hauntd** [comment]
You can also add admin rights to user by using console command:

```
cd application
./yii admin/add your_user_name
```

**Comment by miguel1876** [comment]
Yes I ran the installer.
I'm not sure how to use the console :/

**Comment by miguel1876** [comment]
The 403 error happens  when accessing to the /admin page.  
https://imgur.com/a/j12DZNO
I don't even have a chance to login.

**Comment by hauntd** [comment]
Simply run the terminal, change directory to your website's location, including `/application` at the end and run this:

![image](https://user-images.githubusercontent.com/5505601/46811395-5aa16c00-cd7b-11e8-8506-20232908ad6e.png)

**Comment by hauntd** [comment]
> The 403 error happens when accessing to the /admin page.
> https://imgur.com/a/j12DZNO
> I don't even have a chance to login.

Are you logged in on the site?

**Comment by miguel1876** [comment]
No, I am not logged. I simply installed the script and tried to login by going to the /admin page.
Unless the script logged me in automatically after I installed it?

**Comment by miguel1876** [comment]
Hi Alex.
I got it working.

Thank you for your time.

**Comment by hauntd** [comment]
Ah, I see. You need to login on the site, admin area has no login form. Non-admin users or guests will receive 403 Forbidden error.
