### ISSUE TITLE
Emoticons dont work it shows ? when using emoticons

### ISSUE THREAD

**Issue by bomod** [hauntd/youdate-support#2]
Emoticons not working correctly, it shows ???? when using emoticons 
 For more information, the problem described in the attached pictures.
![2](https://user-images.githubusercontent.com/43688256/46248908-73775c80-c420-11e8-9de0-cbd69ccfea96.PNG)
![3](https://user-images.githubusercontent.com/43688256/46248909-73775c80-c420-11e8-8254-7ffcbfb89d8a.PNG)
![4](https://user-images.githubusercontent.com/43688256/46248910-73775c80-c420-11e8-8d1d-928c7fbf674e.PNG)

**Comment by hauntd** [comment]
Check `.env `file: **DB_CHARSET** value must be **utf8mb4**

**Comment by bomod** [comment]
I'm checking, and i see only **utf8** not **utf8mb4** , when i adding **mb4** its working perfectly

**Comment by bomod** [comment]
Please tell me about cron, im using Cpanel, How i can add cron at Cpanel ?

**Comment by hauntd** [comment]
@bomod https://www.youtube.com/watch?v=WzIqEJkK_pM
