### ISSUE TITLE
Make the profiles privates

### ISSUE THREAD

**Issue by AngryElephant** [hauntd/youdate-support#3]
Hi,

How can i do if i don't want that the profiles be public ? Is there an option for that ? 

Thank you.

**Comment by hauntd** [comment]
Hi,

There's no such option at the moment. 

Please specify what do you mean about private profiles: do not show profile for non-registered users, OR hide profile info completely?

**Comment by AngryElephant** [comment]
Hi,

yes i mean do not show the profiles to unregistered users.

**Comment by hauntd** [comment]
Ok, will add this.

**Comment by AngryElephant** [comment]
Can you indicate how to do by this time ? i mean it's probably just adding the auth middleware on the routes ? (i usually work with laravel, that's how i would do it)

**Comment by hauntd** [comment]
Added option "Hide user profiles from guests" in v1.4
