### ISSUE TITLE
Make folders writable

### ISSUE THREAD

**Issue by AngryElephant** [hauntd/youdate-support#4]
When i try to upload a photo, nothin happened. I have read the documentation and learned that it could be a folder permission issue.

Could you please provide the cmd line to make those folders writables ? This could be provided in install documentation

**Comment by AngryElephant** [comment]
My server is nginx

**Comment by AngryElephant** [comment]
Is it possible to have a quick answer ? this should be in the doc. As for now the script has many issues. It looks nice at first but it's not usable.

**Comment by hauntd** [comment]
```
chmod -R 0775 content
chmod -R 0775 application/runtime
```

**Comment by AngryElephant** [comment]
I did, the images are uploaded but still not displayed

**Comment by AngryElephant** [comment]
Ok i fixed it. The exif extension was not installed. This is not mentioned in the doc ;)
