### ISSUE TITLE
unable to register new user

### ISSUE THREAD

**Issue by kashpal** [hauntd/youdate-support#6]
Hello
I am unable to register new user on the site i dont seem to know what the issue is. please see attached screenshot

You mentioned earlier that it was an smtp connection issue or firewall i have switched to mailgun and still can not get it to work as it should.

Could you please help with this?

Claude 

![error message 2](https://user-images.githubusercontent.com/5859018/46524863-029dcd80-c882-11e8-87e1-19c08393c19e.png)
![error message](https://user-images.githubusercontent.com/5859018/46524864-029dcd80-c882-11e8-9198-8db27ddb6db3.png)
![erros message 3](https://user-images.githubusercontent.com/5859018/46524865-029dcd80-c882-11e8-9797-9b86b8b0e993.png)

**Comment by kashpal** [comment]
I also have this as my mailgun sandbox credentials. can i edit the .env file and what details will i need for it?

SMTP Hostname: smtp.mailgun.org
Default SMTP Login : postmaster@sandbox66c026a01ff144cf83ad17bca71c321b.mailgun.org
Default Password : 475a6ce27b3b210302a4c43db239fe44-c8e745ec-655b256aManage SMTP credentials
API Key : b208ff54ee485ea133951ae5389aef2c-c8e745ec-ac7abb03
API Base URL: https://api.mailgun.net/v3/sandbox66c026a01ff144cf83ad17bca71c321b.mailgun.org

**Comment by hauntd** [comment]
Yes, you can edit .env file. 

For Mailgun you need to update these keys:

```
APP_MAILER_TRANSPORT = smtp
APP_MAILER_HOST = smtp.mailgun.org
APP_MAILER_USERNAME = postmaster@sandbox66c026a01ff144cf83ad17bca71c321b.mailgun.org
APP_MAILER_PASSWORD = 475a6ce27b3b210302a4c43db239fe44-c8e745ec-655b256a
APP_MAILER_PORT = 465
APP_MAILER_ENCRYPTION = ssl
```

**Comment by kashpal** [comment]
i have done this but it still does not work

**Comment by kashpal** [comment]
APP_DEBUG = 1 
APP_ENV = prod
APP_MAILER_TRANSPORT = smtp
APP_MAILER_HOST = smtp.mailgun.org
APP_MAILER_USERNAME = postmaster@sandbox66c026a01ff144cf83ad17bca71c321b.mailgun.org
APP_MAILER_PASSWORD = 475a6ce27b3b210302a4c43db239fe44-c8e745ec-655b256a
APP_MAILER_PORT = 465
APP_MAILER_ENCRYPTION = ssl
APP_MAIL_FROM = postmaster@sandbox66c026a01ff144cf83ad17bca71c321b.mailgun.org

**Comment by hauntd** [comment]
Your config is ok, the problem is on your server (access to smtp.mailgun.org is rejected by hosting provider). Can you contact 1and1 support?

**Comment by kashpal** [comment]
ok i will!

**Comment by kashpal** [comment]
we may have a problem, they dont support smtp smailers only php mailers, is there anyway to fix this?

**Comment by hauntd** [comment]
Ah, I see. PHP mailer is deprecated and removed in SwiftMailer (one of the components). But I have a solution for this, gonna add it soon (v1.3.1).

**Comment by kashpal** [comment]
they have provided me an smtp server details but asked me to set ssl to none even though i have ssl installed

how do i set this to none in .env file?

**APP_MAILER_ENCRYPTION = ssl** should i just put no? or none? or null?

**Comment by kashpal** [comment]
it works now!

thank you for all your help! great support!

Let me give you the steps so that if you have any 1and1 customers it will be easier to support

smtp.1and1.com
port 25
encryption set to TLS - 
1and1 have a managed SSL feature so you dont need to set this to ssl 

thank you very vey much for your help and looking forward to feature updates

**Comment by hauntd** [comment]
Great! I'm glad you've managed to configure the mailer 👍

**Comment by kashpal** [comment]
If its not too much to ask (sorry for too many questions im just very excited about the dating script )

1. Can i get the paths to edit LOGOS on both themes ?
2. Path to edit header and footer on both themes?#

Thank you very much and i will support your work everytime i can

**Comment by kashpal** [comment]
also please provide me the necessary crontabs i need to update as 1and1 has a permission issue for crontabs and does it via php script

**Comment by kashpal** [comment]
path to all emails so i can edit the emails customer receives 👍
