### ISSUE TITLE
How to translate the homepage 

### ISSUE THREAD

**Issue by AngryElephant** [hauntd/youdate-support#7]
is there a file where i can add my own translation ? For example 

`<html lan="en-US"`

i try to find where is this variable : `<html lang="<?= Yii::$app->language ?>">`

I could not find it

**Comment by AngryElephant** [comment]
Where to translate this : Yii::t('app', 'Time zone is not valid')  or this <?= Html::a(Yii::t('youdate', 'Sign in'), ['/security/login'], ['class' => 'btn btn-primary']) ?>

?

**Comment by hauntd** [comment]
Are you using v1.2?

**Comment by hauntd** [comment]
For v1.2+ you can do this in admin panel, a little demo: https://www.dropbox.com/s/vxpfic258rqcghn/language-edit.mov?dl=0 (find your language, activate, edit translations)

**Comment by AngryElephant** [comment]
how do we apply it ? It has to be set by the user ?

**Comment by hauntd** [comment]
Yes, users select their language (but only "active" ones). In v1.3 you'll be able to set default site language (update will be approved soon).

**EDIT:** already approved and available to download.

**Comment by AngryElephant** [comment]
Thanks, i see the update. Any recommendation for updating from 1.2 to 1.3 ? Since i did some modifications in youdate theme already

**Comment by AngryElephant** [comment]
Can you tell me how to upgrade ? At least for language ?

**Comment by hauntd** [comment]
Replace `application` directory, run website/admin area. Script will try to apply updates automatically.

If this doesn't help, you can do this manually (after replacing `application` directory):
```
cd application
./yii migrate/up
./yii cache/flush-all

```

**Comment by AngryElephant** [comment]
Thanks for your help. 

Now i updated the script, i switched the language but on my theme, it's still english, (login page, registration, homepage...)

**Comment by AngryElephant** [comment]
Also in the custom theme, i can't add images in custom/static/images/ to customize the theme, @themeUrl refer to the parent theme which is youdate, the images are 404

**Comment by hauntd** [comment]
> Thanks for your help.
> 
> Now i updated the script, i switched the language but on my theme, it's still english, (login page, registration, homepage...)

There's a checkbox "Autodetect language based on user's browser language", when checked script will try to set language automatically. Is it checked?



> Also in the custom theme, i can't add images in custom/static/images/ to customize the theme, @themeUrl refer to the parent theme which is youdate, the images are 404

I'll investigate. You can also try this (more versatile): 

`@web/content/themes/youdate/static/images/logo@2x.png`

or `@web/content/themes/custom/static/images/logo@2x.png` (depends on where your logo is)
