### ISSUE TITLE
Hide twitter connect?

### ISSUE THREAD

**Issue by appache7-2** [hauntd/youdate-support#8]
Hello,
Can you tell me how to Hide twitter connect?

tx

**Comment by appache7-2** [comment]
i make a 
display: none 
on 
.btn-twitter
Good

**Comment by hauntd** [comment]
Hello,

> i make a
> display: none
> on
> .btn-twitter
> Good

Yes, this should work :) Gonna add a better solution on next update.

**Comment by hauntd** [comment]
Updated in v1.4
